import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const UIContext = createContext({
    theme: 'dark',
    language: 'vi',
    toggleTheme: () => { },
    toggleLanguage: () => { },
    t: (key) => key,
    colors: {
        background: 'bg-[#0A0A0F]',
        card: 'bg-[#141420]',
        border: 'border-[#1E1E2E]',
        text: 'text-white',
        textSecondary: 'text-gray-500',
        textMuted: 'text-gray-600',
        primary: '#00D4FF',
        accent: '#F4C430',
        statusBarStyle: 'light-content',
        headerBg: 'bg-[#0A0A0F]',
    }
});

export const UIProvider = ({ children }) => {
    const [theme, setTheme] = useState('dark'); // 'dark' or 'light'
    const [language, setLanguage] = useState('vi'); // 'en' or 'vi'

    useEffect(() => {
        loadSettings();
    }, []);

    const loadSettings = async () => {
        try {
            const savedTheme = await AsyncStorage.getItem('theme');
            const savedLang = await AsyncStorage.getItem('language');
            if (savedTheme) setTheme(savedTheme);
            if (savedLang) setLanguage(savedLang);
        } catch (error) {
            console.error('Failed to load UI settings:', error);
        }
    };

    const toggleTheme = async () => {
        const newTheme = theme === 'dark' ? 'light' : 'dark';
        setTheme(newTheme);
        await AsyncStorage.setItem('theme', newTheme);
    };

    const toggleLanguage = async () => {
        const newLang = language === 'en' ? 'vi' : 'en';
        setLanguage(newLang);
        await AsyncStorage.setItem('language', newLang);
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    const colors = theme === 'dark' ? {
        background: 'bg-[#0A0A0F]',
        card: 'bg-[#141420]',
        border: 'border-[#1E1E2E]',
        text: 'text-white',
        textSecondary: 'text-gray-500',
        textMuted: 'text-gray-600',
        primary: '#00D4FF',
        accent: '#F4C430',
        statusBarStyle: 'light-content',
        headerBg: 'bg-[#0A0A0F]',
    } : {
        background: 'bg-[#F8F9FA]',
        card: 'bg-white',
        border: 'border-gray-200',
        text: 'text-[#0A0A0F]',
        textSecondary: 'text-gray-600',
        textMuted: 'text-gray-400',
        primary: '#00D4FF',
        accent: '#E6B800',
        statusBarStyle: 'dark-content',
        headerBg: 'bg-white',
    };

    return (
        <UIContext.Provider value={{ theme, language, toggleTheme, toggleLanguage, t, colors }}>
            {children}
        </UIContext.Provider>
    );
};

export const useUI = () => useContext(UIContext);

const translations = {
    en: {
        welcome: 'Welcome back',
        signin_continue: 'Sign in to continue',
        email: 'EMAIL',
        password: 'PASSWORD',
        remember_me: 'Remember me',
        forgot_password: 'Forgot password?',
        signin: 'SIGN IN',
        no_account: "Don't have an account?",
        signup: 'Sign up',
        account: 'ACCOUNT',
        personal_info: 'Personal Info',
        notifications: 'Notifications',
        language: 'Language',
        security: 'Security',
        theme: 'Theme',
        rate_app: 'Rate the App',
        support: 'Customer Support',
        sign_out: 'SIGN OUT',
        now_showing: 'Now Showing',
        see_all: 'See all',
        exclusive_offers: 'Vouchers',
        hanoi: 'Ha Noi',
        search_placeholder: 'Search movies, genres...',
        movies: 'MOVIES',
        tickets: 'VOUCHERS',
        rating: 'RATING',
        gold_member: 'Gold Member',
        my_tickets: 'My Vouchers',
        wallet: 'CineViet Wallet',
        offers: 'Vouchers',
        points: 'Reward Points',
        upcoming: 'Upcoming',
        available: 'available',
        save: 'Save',
        book_now: 'BOOK NOW',
        create_account: 'Create your account',
        already_have_account: 'Already have an account?',
        confirm_password: 'CONFIRM PASSWORD',
        full_name: 'FULL NAME',
        all: 'All',
        watched: 'Watched',
        cancelled: 'Cancelled',
        no_tickets_yet: 'No bookings yet',
        book_first_ticket: 'Book your first ticket and enjoy the cinema experience!',
        explore_movies: 'Explore Movies',
        room: 'ROOM',
        date: 'DATE',
        time: 'TIME',
        seats: 'SEATS',
        synopsis: 'SYNOPSIS',
        cast: 'CAST',
        director: 'DIRECTOR',
        producer: 'PRODUCER',
        format: 'FORMAT',
        share: 'SHARE',
        movie_desc_placeholder: 'Movie description is being updated. Stay tuned for this masterpiece at CINEVIET.',
        cast_placeholder: 'The cast list for this movie is currently being updated. Check back soon for details.',
        director_placeholder: 'CineViet Studios',
        producer_placeholder: 'Global Media Productions Inc.',
        seat_selection: 'SEAT SELECTION',
        theater_layout: 'THEATER LAYOUT',
        screen: 'SCREEN',
        legend: 'LEGEND',
        open: 'OPEN',
        sold: 'SOLD',
        vip: 'VIP',
        couple: 'COUPLE',
        selected: 'Selected: ',
        none: 'None',
        loading_theater: 'Loading Theater...',
        loading_movie: 'Loading Movie...',
        save_changes: 'SAVE CHANGES',
        order_summary: 'Order Summary',
        tickets_count: 'Tickets',
        promo: 'Promo',
        apply_promo: 'Apply Promo Code',
        tap_view_offers: 'Tap to view available offers',
        saved_badge: 'SAVED',
        terms_policy_note: "By confirming, you agree to CINEVIET's Terms of Service and Refund Policy.",
        your_offers: 'YOUR OFFERS',
        offers_available: 'offers available',
        no_offers: 'No offers available',
        applicable_all: 'Applicable to all screenings.',
        no_discount: 'No discount',
        total_amount: 'Total amount',
        pay_now: 'PAY NOW',
        vnpay_paid: 'VNPAY Paid',
        my_booking_title: 'My Booking',
        special_offer_note: 'Special offer for CineViet fans. Use at checkout.',
        expires: 'Expires',
        applied: 'Applied',
        confirm_booking: 'Confirm Booking',
        payment_complete: 'Payment Complete',
        booking_confirmed: 'BOOKING CONFIRMED!',
        booking_code: 'Booking Code',
        cinema: 'Cinema',
        date_time: 'Date & Time',
        total_paid: 'Total Paid',
        ticket_email_note: 'Your ticket has been sent to your email. Show the booking code at the cinema entrance.',
        view_my_tickets: 'VIEW MY TICKETS',
        browse_more: 'Browse More Movies',
        payment_failed: 'Payment Failed',
        payment_failed_msg: 'Your payment was not successful. Seats have been released.',
        loading_booking: 'LOADING BOOKING DETAILS...',
        ticket_display_note: 'Ticket will be shown after payment',
        reorder: 'Reorder',
        my_tickets_title: 'My Tickets',
        no_tickets_found: 'No tickets found',
        room_label: 'Room',
        error: 'Error',
        success: 'Success',
        notice: 'Notice',
        promo_failed: 'Promo code cannot be applied',
        choose_other_promo: 'Please choose another promo',
        edit_profile: 'Edit Profile',
        full_name: 'Full Name',
        current_password: 'Current Password',
        new_password: 'New Password',
        change_password_optional: 'Change Password (Optional)',
        app_settings: 'App Settings',
        confirm: 'Confirm',
        confirm_sign_out: 'Are you sure you want to sign out?',
        cancel: 'Cancel',
        continue: 'CONTINUE',
        step: 'Step',
        weak_password: 'Weak password',
        medium_strength: 'Medium strength',
        strong_password: 'Strong password ✓',
        passwords_not_match: 'Passwords do not match',
        terms_agreement_1: 'I agree to the ',
        terms_agreement_2: 'Terms of Service',
        terms_agreement_3: ' and ',
        terms_agreement_4: 'Privacy Policy',
        enter_email: 'Please enter your email',
        enter_full_name: 'Please enter your full name',
        password_min_length: 'Password must be at least 6 characters',
        agree_terms: 'Please agree to the Terms of Service',
        registration_failed: 'Registration Failed',
        coming_soon: 'Coming Soon',
        social_signup_note: 'Sign up with {{provider}} will be available soon!',
        your_name: 'Your name',
        your_email: 'Your email',
        dark: 'Dark',
        light: 'Light',
    },
    vi: {
        welcome: 'Chào mừng quay trở lại',
        signin_continue: 'Đăng nhập để tiếp tục',
        email: 'EMAIL',
        password: 'MẬT KHẨU',
        remember_me: 'Ghi nhớ đăng nhập',
        forgot_password: 'Quên mật khẩu?',
        signin: 'ĐĂNG NHẬP',
        no_account: 'Chưa có tài khoản?',
        signup: 'Đăng ký ngay',
        account: 'TÀI KHOẢN',
        personal_info: 'Thông tin cá nhân',
        notifications: 'Thông báo',
        language: 'Ngôn ngữ',
        security: 'Bảo mật',
        theme: 'Giao diện',
        rate_app: 'Đánh giá ứng dụng',
        support: 'Hỗ trợ khách hàng',
        sign_out: 'ĐĂNG XUẤT',
        now_showing: 'Phim đang chiếu',
        see_all: 'Xem tất cả',
        exclusive_offers: 'Voucher',
        hanoi: 'Hà Nội',
        search_placeholder: 'Tìm kiếm phim, thể loại...',
        movies: 'PHIM',
        tickets: 'VOUCHER',
        rating: 'ĐÁNH GIÁ',
        gold_member: 'Thành viên Vàng',
        my_tickets: 'Voucher của tôi',
        wallet: 'Ví CineViet',
        offers: 'Voucher',
        points: 'Điểm tích lũy',
        upcoming: 'Sắp tới',
        available: 'có sẵn',
        save: 'Tiết kiệm',
        book_now: 'ĐẶT VÉ NGAY',
        create_account: 'Tạo tài khoản mới',
        already_have_account: 'Đã có tài khoản?',
        confirm_password: 'XÁC NHẬN MẬT KHẨU',
        full_name: 'HỌ VÀ TÊN',
        all: 'Tất cả',
        watched: 'Đã xem',
        cancelled: 'Đã hủy',
        no_tickets_yet: 'Chưa có đơn đặt nào',
        book_first_ticket: 'Hãy đặt vé ngay để trải nghiệm điện ảnh tuyệt vời!',
        explore_movies: 'Khám phá phim ngay',
        room: 'PHÒNG',
        date: 'NGÀY',
        time: 'GIỜ',
        seats: 'GHẾ',
        synopsis: 'TÓM TẮT',
        cast: 'DIỄN VIÊN',
        director: 'ĐẠO DIỄN',
        producer: 'NHÀ SẢN XUẤT',
        format: 'ĐỊNH DẠNG',
        share: 'CHIA SẺ',
        movie_desc_placeholder: 'Mô tả phim đang được cập nhật. Hãy đón chờ siêu phẩm này tại CINEVIET.',
        cast_placeholder: 'Danh sách diễn viên đang được cập nhật. Vui lòng quay lại sau.',
        director_placeholder: 'Xưởng phim CineViet',
        producer_placeholder: 'Công ty sản xuất Global Media',
        seat_selection: 'CHỌN GHẾ',
        theater_layout: 'SƠ ĐỒ PHÒNG CHIẾU',
        screen: 'MÀN HÌNH',
        legend: 'CHÚ THÍCH',
        open: 'TRỐNG',
        sold: 'ĐÃ ĐẶT',
        vip: 'VIP',
        couple: 'GHẾ ĐÔI',
        selected: 'Đã chọn: ',
        none: 'Chưa có',
        loading_theater: 'Đang tải phòng chiếu...',
        loading_movie: 'Đang tải thông tin phim...',
        save_changes: 'LƯU THAY ĐỔI',
        order_summary: 'Chi tiết đơn hàng',
        tickets_count: 'Vé',
        promo: 'Khuyến mãi',
        apply_promo: 'Áp dụng mã giảm giá',
        tap_view_offers: 'Nhấn để xem các ưu đãi có sẵn',
        saved_badge: 'ĐÃ GIẢM',
        terms_policy_note: 'Bằng việc xác nhận, bạn đồng ý với Điều khoản dịch vụ và Chính sách hoàn tiền của CINEVIET.',
        your_offers: 'ƯU ĐÃI CỦA BẠN',
        offers_available: 'ưu đãi có sẵn',
        no_offers: 'Không có ưu đãi nào',
        applicable_all: 'Áp dụng cho tất cả các suất chiếu.',
        no_discount: 'Không sử dụng mã',
        total_amount: 'Tổng thanh toán',
        pay_now: 'THANH TOÁN NGAY',
        vnpay_paid: 'Đã thanh toán qua VNPAY',
        my_booking_title: 'Đơn hàng của tôi',
        special_offer_note: 'Ưu đãi đặc biệt dành cho fan CineViet. Sử dụng khi thanh toán.',
        expires: 'Hết hạn',
        applied: 'Đã áp dụng',
        confirm_booking: 'Xác nhận đặt vé',
        payment_complete: 'Thanh toán hoàn tất',
        booking_confirmed: 'ĐẶT VÉ THÀNH CÔNG!',
        booking_code: 'Mã đặt vé',
        cinema: 'Rạp',
        date_time: 'Ngày & Giờ',
        total_paid: 'Tổng tiền đã thanh toán',
        ticket_email_note: 'Vé đã được gửi đến email của bạn. Vui lòng xuất trình mã đặt vé tại quầy soát vé.',
        view_my_tickets: 'XEM VÉ CỦA TÔI',
        browse_more: 'Khám phá thêm phim',
        payment_failed: 'Thanh toán thất bại',
        payment_failed_msg: 'Thanh toán của bạn không thành công. Ghế đã được giải phóng.',
        loading_booking: 'ĐANG TẢI THÔNG TIN VÉ...',
        ticket_display_note: 'Vé sẽ được hiển thị sau khi thanh toán',
        reorder: 'Đặt lại',
        my_tickets_title: 'Vé Của Tôi',
        no_tickets_found: 'Bạn chưa có vé nào',
        room_label: 'Phòng',
        error: 'Lỗi',
        success: 'Thành công',
        notice: 'Thông báo',
        promo_failed: 'Không áp dụng được mã giảm giá',
        choose_other_promo: 'Vui lòng chọn mã khác',
        edit_profile: 'Chỉnh sửa hồ sơ',
        full_name: 'Họ và tên',
        current_password: 'Mật khẩu hiện tại',
        new_password: 'Mật khẩu mới',
        change_password_optional: 'Đổi mật khẩu (Không bắt buộc)',
        app_settings: 'Cài đặt ứng dụng',
        confirm: 'Xác nhận',
        confirm_sign_out: 'Bạn có chắc chắn muốn đăng xuất?',
        cancel: 'Hủy',
        'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.': 'Một kẻ trộm chuyên nghiệp có khả năng xâm nhập vào tiềm thức của người khác thông qua giấc mơ để đánh cắp các bí mật tập đoàn. Anh ta được giao một nhiệm vụ ngược lại: cấy một ý tưởng vào tâm trí của một CEO.',
        'A thief who steals corporate secrets through dream-sharing technology.': 'Một kẻ trộm chuyên nghiệp có khả năng xâm nhập vào tiềm thức của người khác thông qua giấc mơ để đánh cắp các bí mật tập đoàn.',
    }
};
